name = "NiLangCore"
uuid = "575d3204-02a4-11ea-3f62-238caa8bf11e"
authors = ["JinGuo Liu", "thautwarm"]
version = "0.8.3"

[deps]
MatchCore = "5dd3f0b1-72a9-48ad-ae6e-79f673da005f"
TupleTools = "9d95972d-f1c8-5527-a6e0-b4b365fa01f6"

[compat]
MatchCore = "0.1"
TupleTools = "1.2"
julia = "1.3,1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
